apiVersion: v1
kind: Service
metadata:
  name: dotnetaksdemo
  namespace: namespace-workflow-1741246324938
  labels:
    app.kubernetes.io/name: dotnetaksdemo
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dotnetaksdemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000